#!/bin/bash

case "$1" in 
start)
   /usr/bin/ubic &
   echo $!>/var/run/ubic.pid
   ;;
stop)
   kill `cat /var/run/ubic.pid`
   rm /var/run/ubic.pid
   ;;
restart)
   $0 stop
   sleep 4
   $0 start
   ;;
status)
   if [ -e /var/run/ubic.pid ]; then
      echo ubic is running, pid=`cat /var/run/ubic.pid`
   else
      echo ubic is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
